#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tds
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tds-repo
spec:
  fetch:
    imgpkgBundle:
      #@ if data.values.platformRegistryLocation == 'customPlatformRegistrySelection':
      image: #@ data.values.customPlatformTdsRegistry + '/tds-packages:1.12.0'
      #@ else:
      image: "registry.tanzu.vmware.com/packages-for-vmware-tanzu-data-services/tds-packages:1.12.0"
      #@ end
      #!secretRef:
        #!name: install-registry-dockerconfig